export default [
  "src/DoricPlayground",
  "src/Gobang",
  "src/Snake",
  "src/DuadGame",
  "src/Examples",
  "src/HelloDoric",
  "src/Counter",
  "src/Image",
  "src/Modal",
  "src/Storage",
  "src/Popover",
  "src/Draggable",
  "src/Poetry",
  "src/Debug",
  "src/FileManager",
];
